package POJOS;
// Generated 27-may-2016 11:01:44 by Hibernate Tools 4.3.1


import POJOS.*;
import java.util.Date;
import javax.persistence.Column;
import org.hibernate.annotations.Type;

/**
 * Coordenadas generated by hbm2java
 */
public class Coordenadas  implements java.io.Serializable {


     private Integer id;
     private String glatitud;
     private String glongitud;
    @Column
    @Type(type="date")
     private Date date;
     private Integer usuariosId;

     
     @Override
    public boolean equals(Object object) {
        if (object == null) {
            return false;
        } else if (!(object instanceof Usuarios)) {
            return false;
        } 
        else 
        {
            Coordenadas c = (Coordenadas) object;
            if (usuariosId.equals(c.getUsuariosId()) && (date.equals(c.getDate()))) 
            {
                return true;
            }
        }
        return false;
    }

    @Override
    public String toString() {
        String cadena = id + "," + glatitud + "," + glongitud + "," + date + "," + usuariosId;
        return cadena;
    }
     
    public Coordenadas() {
    }

    public Coordenadas(String glatitud, String glongitud, Date date, Integer usuariosId) {
       this.glatitud = glatitud;
       this.glongitud = glongitud;
       this.date = date;
       this.usuariosId = usuariosId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGlatitud() {
        return this.glatitud;
    }
    
    public void setGlatitud(String glatitud) {
        this.glatitud = glatitud;
    }
    public String getGlongitud() {
        return this.glongitud;
    }
    
    public void setGlongitud(String glongitud) {
        this.glongitud = glongitud;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getUsuariosId() {
        return this.usuariosId;
    }
    
    public void setUsuariosId(Integer usuariosId) {
        this.usuariosId = usuariosId;
    }




}


