package POJOS;
// Generated 27-may-2016 11:01:44 by Hibernate Tools 4.3.1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas implements java.io.Serializable {

    private Integer id;
    private String cif;
    private String nombre;
    private String direccion;
    private String provincia;
    private String poblacion;
    private String cp;
    private int tlf;
    private int comercial;
    private Date fechaAlta;
    private String contacto;
    private Set visitases = new HashSet(0);

    @Override
    public boolean equals(Object object) {
        if (object == null) {
            return false;
        } else if (!(object instanceof Empresas)) {
            return false;
        } else {
            Empresas e = (Empresas) object;
            if (id == e.getId()
                    && nombre.equals(e.getNombre())
                    && cif.equals(e.getCif())) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String toString() {
        String cadena = id + "," + cif + "," + nombre + "," + direccion + "," + provincia + "," + poblacion + "," + cp + "," + tlf + "," + comercial + "," + fechaAlta + "," + contacto;
        return cadena;
    }

    public Empresas() {
    }

    public Empresas(String cif, String nombre, String direccion, String provincia, String poblacion, String cp, int tlf, int comercial, String contacto) {
        this.cif = cif;
        this.nombre = nombre;
        this.direccion = direccion;
        this.provincia = provincia;
        this.poblacion = poblacion;
        this.cp = cp;
        this.tlf = tlf;
        this.comercial = comercial;
        this.fechaAlta = new Date();
        this.contacto = contacto;
        this.visitases = null;

    }

    public Empresas(String cif, String nombre, String direccion, String provincia, String poblacion, String cp, int tlf, int comercial, Date fechaAlta, String contacto, Set visitases) {
        this.cif = cif;
        this.nombre = nombre;
        this.direccion = direccion;
        this.provincia = provincia;
        this.poblacion = poblacion;
        this.cp = cp;
        this.tlf = tlf;
        this.comercial = comercial;
        this.fechaAlta = fechaAlta;
        this.contacto = contacto;
        this.visitases = visitases;
    }

    public Empresas(List<String> lista) {
        this.id = Integer.parseInt(lista.get(0));
        this.cif = lista.get(1);
        this.nombre = lista.get(2);
        this.direccion = lista.get(3);
        this.provincia = lista.get(4);
        this.poblacion = lista.get(5);
        this.cp = lista.get(6);
        this.tlf = Integer.parseInt(lista.get(7));
        this.comercial = Integer.parseInt(lista.get(8));
        /*SimpleDateFormat fecha = new SimpleDateFormat("yyyy-MM-dd");
            Date fnac = null;
            try {
                fnac = fecha.parse(datos.split(",")[3]);
            } catch (ParseException ex) {
                System.err.print("exception con la fecha " + ex);
            }*/
        SimpleDateFormat fecha = new SimpleDateFormat("yyyy-MM-dd");
        Date f = null;
        try {
            f = fecha.parse(lista.get(9));
        } catch (ParseException ex) {
            System.err.print("exception con la fecha en contructor empresa " + ex);
        }
        this.fechaAlta = f;
        this.contacto = lista.get(10);

    }

    public Empresas(String nombre, String direccion, String provincia, String poblacion, String cp, int tlf, int comercial, Date fechaAlta) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.provincia = provincia;
        this.poblacion = poblacion;
        this.cp = cp;
        this.tlf = tlf;
        this.comercial = comercial;
        this.fechaAlta = fechaAlta;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCif() {
        return this.cif;
    }

    public void setCif(String cif) {
        this.cif = cif;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getPoblacion() {
        return this.poblacion;
    }

    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    public int getTlf() {
        return this.tlf;
    }

    public void setTlf(int tlf) {
        this.tlf = tlf;
    }

    public int getComercial() {
        return this.comercial;
    }

    public void setComercial(int comercial) {
        this.comercial = comercial;
    }

    public Date getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    public String getContacto() {
        return this.contacto;
    }

    public void setContacto(String contacto) {
        this.contacto = contacto;
    }

    public Set getVisitases() {
        return this.visitases;
    }

    public void setVisitases(Set visitases) {
        this.visitases = visitases;
    }

}
