package POJOS;
// Generated 02-may-2016 18:45:51 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import org.hibernate.engine.spi.SessionImplementor;

/**
 * Visitas generated by hbm2java
 */
@XmlRootElement(name = "Visitas")
public class Visitas  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private Usuarios usuarios;
     private Date fecha;
     private String resultado;
     private String motivo;

    public Visitas() {
    }

	
    public Visitas(Empresas empresas, Usuarios usuarios, Date fecha) {
        this.empresas = empresas;
        this.usuarios = usuarios;
        this.fecha = fecha;
    }
    public Visitas(Empresas empresas, Usuarios usuarios, Date fecha, String resultado, String motivo) {
       this.empresas = empresas;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.resultado = resultado;
       this.motivo = motivo;
    }
    @XmlElement
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @XmlElement
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    
    @XmlElement
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    
    @XmlElement
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @XmlElement
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    
    @XmlElement
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    @Override
    public String toString() 
    {
        String cadena=id+","+empresas+","+usuarios+","+fecha+","+resultado+","+motivo;
        
        return cadena;
    }
    
    
    @Override
   public boolean equals(Object object){
      if(object == null){
         return false;
      }else if(!(object instanceof Usuarios)){
         return false;
      }else {
         Visitas v = (Visitas)object;
         if(id.equals(v.getId()) && (empresas.equals(v.getEmpresas()))  && (usuarios.equals(v.getUsuarios())))
         {
            return true;
         }			
      }
      return false;
   }



}


